version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5431:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: dev

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
